=== polms/pacman/niveau.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:simpleType name="ghosts">
        <xs:restriction base="xs:string">
            <xs:enumeration value="inky" />
            <xs:enumeration value="pinky" />
            <xs:enumeration value="clide" />
            <xs:enumeration value="blinky" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="tvgomes">
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
                <xs:attribute name="time" use="required" type="xs:nonNegativeInteger"/><!-- Peux être zero pour désactiver le temps de d'invincibilité -->
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
        <xs:simpleType name="coords">
            <xs:restriction base="xs:nonNegativeInteger">
                <xs:minInclusive value="0"/>
                <xs:maxInclusive value="30"/> <!-- On a choisi une taille de plateau de 30 par 30 -->
            </xs:restriction>
        </xs:simpleType>
    <xs:element name="game"> <!-- Liste des sections du fichier-->
        <xs:complexType>
            <xs:all>
                <xs:element ref="level"/>
                <xs:element ref="speed"/>
                <xs:element ref="player-lives"/>
                <xs:element ref="best-score"/>
                <xs:element ref="gomes-values"/>
                <xs:element ref="start-positions"/>
                <xs:element ref="plateau"/>
            </xs:all>
        </xs:complexType>
        <xs:unique name="NoDuplicateCoordinates"> <!-- Deux entitées ne peuvent pas êtres à la même position -->
            <xs:selector xpath=".//*"/>
            <xs:field xpath="@x"/>
            <xs:field xpath="@y"/>
        </xs:unique>
    </xs:element>
    <xs:element name="level" type="xs:positiveInteger"/>
    <xs:element name="speed" type="xs:positiveInteger"/>
    <xs:element name="player-lives" type="xs:positiveInteger"/>
    <xs:element name="best-score" type="xs:nonNegativeInteger"/> <!-- un score de 0 signale que c'est la première partie jouée -->
    <xs:element name="gomes-values">
        <xs:complexType>
            <xs:all>
                <xs:element name="super-gome" type="tvgomes"/>
                <xs:element name="gome" type="tvgomes"/>
                <xs:element name="bonus" type="tvgomes"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="start-positions">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="1" ref="pacman"/>
                <xs:element ref="ghost" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="NoDuplicateGhost">
            <xs:selector xpath="ghost"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>
    <xs:element name="pacman">
        <xs:complexType>
            <xs:attribute name="x" use="required" type="coords"/>
            <xs:attribute name="y" use="required" type="coords"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ghost">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="ghosts">
                    <xs:attribute name="x" use="required" type="coords"/>
                    <xs:attribute name="y" use="required" type="coords"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="plateau">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:pattern value="[SNB■ \n]*"/> <!-- S indique une super-gomme, N une gomme normale, B une gomme bonus et ■ un mur -->
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
</xs:schema>

=== polms/pacman/map1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="niveau.xsd">
        <level>1</level>
        <speed>500</speed>
        <player-lives>5</player-lives>

        <best-score>786</best-score>

        <gomes-values>
                <super-gome time="5000">10</super-gome>
                <gome time="3000">3</gome>
                <bonus time="7000">15</bonus>
        </gomes-values>

        <start-positions>
                <pacman x="1" y="2"/>
                <ghost x="1" y="4">inky</ghost>
                <ghost x="4" y="2">pinky</ghost>
                <ghost x="27" y="4">clide</ghost>
                <ghost x="22" y="10">blinky</ghost>
        </start-positions>

        <plateau>
          ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■
          ■ N N N N N N N N N N N N N ■ N N N N N N N N N N N N N N ■
          ■ N ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ N ■ N ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ N ■
          ■ S ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ N ■ N ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ S ■
          ■ N ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ N ■ N ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ N ■
          ■ N N N N N N N N N N N N N N N N N N N N N N N N N N N N ■
          ■ N ■ ■ ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ N ■
          ■ N ■ ■ ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ N ■
          ■ N N N N N N ■ ■ ■ N N N N N N N N N ■ ■ ■ N N N N N N N ■
          ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■
          ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■
          ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■
          ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■
          ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■
          ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■ ■ N N N N N N N N ■ ■ ■ ■ ■ ■ ■
          ■ ■ ■ ■ ■ ■ N N N N N ■ ■ ■ N N ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■
          ■ ■ ■ ■ ■ ■ N ■ ■ ■ N ■ ■ N S ■ ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■
          ■ ■ ■ ■ ■ ■ N ■ ■ ■ N N N N ■ ■ ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■
          ■ ■ ■ ■ ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■
          ■ ■ ■ ■ ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■
          ■ ■ ■ ■ ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■
          ■ N N N N N N ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■ N N N N N N N S N N N ■
          ■ N ■ ■ ■ ■ N ■ ■ ■ N ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ N ■
          ■ N ■ ■ ■ ■ N ■ ■ ■ N ■ N N N S ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ N ■
          ■ S ■ ■ ■ ■ N ■ ■ ■ N ■ N ■ ■ N ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ N ■
          ■ N ■ ■ ■ ■ N ■ ■ ■ N ■ N ■ ■ N ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ N ■
          ■ N ■ ■ ■ ■ N ■ ■ ■ N ■ N ■ ■ N ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ N ■
          ■ N ■ ■ ■ ■ N ■ ■ ■ N ■ N ■ ■ N ■ ■ ■ ■ ■ ■ N ■ ■ ■ ■ ■ N ■
          ■ N N N N N N N N N N N N N N N N N N N N N N N N N N N N ■
          ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■
        </plateau>
</game>
